### ISSUE TITLE
Box2D utilities module

### ISSUE THREAD

**Issue by czyzby** [libktx/ktx#52]
- [x] Review [gdx-box2d-kotlin](https://github.com/Jkly/gdx-box2d-kotlin) code.
- ~~Migrate gdx-box2d-kotlin to `ktx-box2d` module.~~
- [x] `FixtureDef` factory methods supporting different shapes.
- [x] `earthGravity` property.
- [x] `World` factory methods.
- [x] Documentation listing all extensions. Usage examples.
- [x] Provide an easy way to access built `Fixture` instances.
- [x] Improve `FixtureDef.filter` API.
- [x] Address `FixtureDef.shape` issue.
- [x] Add `userData` properties to extended body and fixture definitions.

---

@Jkly

**Comment by czyzby** [comment]
@Jkly I'm sorry, but I just don't like the approach of wrappers of the original Box2D API. Not only you have to maintain and test the existing properties, but also you don't immediately support new ones added in LibGDX. (Well, not that it happens very often, but still.) I prefer to add extension methods and some inlined building utilities to existing Box2D classes. This is the API I'm aiming for:

```Kotlin
world.body {
  type = DynamicBody
  bullet = true
  circle(radius = 3f) {
    restitution = 0.5f
  }
}
```

I'll still credit you for the original idea with link to the repo in the `README` file.

**Comment by Jkly** [comment]
Sure, no problem - I agree with the problem of wrapping the API, it's just sufficed for what I've needed so far. I'll definitely be interested in whatever you come up with  😄

**Comment by czyzby** [comment]
Done. I've implemented the initial set of Box2D utilities - I believe it covers most of `gdx-box2d-kotlin` features. [You can find them on the `develop` branch.](https://github.com/libktx/ktx/tree/develop/box2d) I'd appreciate it if you checked it out. You can also post new utilities suggestions at #65.

**Comment by Jkly** [comment]
@czyzby It looks good from what I've looked at so far. The better coverage of the shape types is great and not having to maintain duplicate properties will definitely make maintenance much easier. 

Just a couple of things from a quick look:
* It's possible to set the shape again from the fixture closure. e.g. 
```
val body = world.body {
      type = DynamicBody
      circle(radius = 2f) {
        shape = PolygonShape() // causes runtime error
        density = 0.5f
      }
    }

```
* It might be worth creating a `FixtureDefinition` like you did with `BodyDef` to try and hide access to `FixtureDef.shape`? 
* One thing that was useful in gdx-box2d-kotlin was being able to provide a callback function that received the instantiated fixture, so that the reference could be used elsewhere in game code.

**Comment by czyzby** [comment]
> * It might be worth creating a `FixtureDefinition` like you did with `BodyDef` to try and hide access to `FixtureDef.shape`?

Manually modifying `shape` field is a misuse of the API, but I can see why you'd consider it a problem. `FixtureDef` defines a `shape` _field_ rather than getter and setter pair than you can override. I don't think you can modify field access modifier, and adding a `shape` Kotlin property just makes the API unusable (no quickfix suggestions).

```
Overload resolution ambiguity. All these functions match.
* public final val shape: Shape defined in ktx.box2d.FixtureDefinition
* public final var shape: Shape! defined in ktx.box2d.FixtureDefinition
```

If you can think of a way of hiding the field without replicating `FixtureDef` class, I can implement that.

> * One thing that was useful in gdx-box2d-kotlin was being able to provide a callback function that received the instantiated fixture, so that the reference could be used elsewhere in game code.

Yeah, I've noticed that `Fixtures` are pretty hard to access. I'll think of something.

**Comment by Jkly** [comment]
I think I see being able to modify `FixtureDef.shape` more of an issue for providing a safe API, but actually isn't a show-stopper for me.

One minor thing - for `circle()`, I think it's more useful to be able to pass the offset as a `Vector2` rather than separate `x`, `y` params in case the API user has one instantiated already.

**Comment by Jkly** [comment]
Also, it'll be useful to have this extension function:
`fun FixtureDef.filter(filter: Filter.() -> Unit)`

so you could do (would also be less maintenance):
```
    world.body {
      type = DynamicBody
      circle(radius = 2f) {
        density = 0.5f
        filter {
          groupIndex = 1
        }
      }
    }

```

**Comment by Jkly** [comment]
This worked for me, in terms of hiding `FixtureDef.shape`:
```
  class FixtureDefinition : FixtureDef() {
    val shape: Any? = null
  }

  inline fun <ShapeType : Shape> fixture(
      shape: ShapeType,
      init: (@Box2DDsl FixtureDefinition).(ShapeType) -> Unit): FixtureDef {
    val fixture = FixtureDefinition()
    (fixture as FixtureDef).shape = shape
    fixture.init(shape)
    fixtureDefinitions.add(fixture)
    return fixture
  }
```

**Comment by czyzby** [comment]
> One minor thing - for `circle()`, I think it's more useful to be able to pass the offset as a `Vector2` rather than separate `x`, `y` params in case the API user has one instantiated already.

I think I originally went for separate `x` and `y` primitives to create less garbage (as it seems the LibGDX way of doing things), but `circle.position.set(x, y)` was ignored - it makes no JNI call and does not actually change the fixture offset. Since now the method internally creates a new `Vector2` either way, it makes sense to expose it as a parameter.

> Also, it'll be useful to have this extension function: (...)

Makes sense. I'll replace the 3-argument `filter` function with this. Thanks.

> This worked for me, in terms of hiding `FixtureDef.shape`:

The class itself compiles and with casting you can access the shape, but the users of the API cannot access the shape from within fixture definition scope. Try this:

```Kotlin
FixtureDefinition().shape
```

It makes it impossible to override the field without casting, but also forbids you from using the getter. It feels like a hack, really, I'd rather just leave the `shape` alone and add a warning in the documentation. It's a clear misuse of the unfortunate LibGDX API.

**Comment by czyzby** [comment]
There's one mayor issue with callbacks: even when inlined, compiler won't allow you to assign vals there. Building an immutable Box2D entity with all necessary references should be trivial and free of `lateinit`. I think `Body` extensions will address that:

```Kotlin
class MyEntity(world: World) {
  val body = world.body {
    circle { /* Define fixtures that you don't need access to here. */ }
  }
  val importantFixture = body.box { /* Define other fixtures outside of the main building block. */ }
}

**Comment by Jkly** [comment]
> It makes it impossible to override the field without casting, but also forbids you from using the getter

I see your point now. I think it's unlikely users will try setting `FixtureDef.shape` again, so not hiding it is fine.

> There's one mayor issue with callbacks: even when inlined, compiler won't allow you to assign vals there

The callbacks have been useful in some of my game code where I have this pattern:
```
    private fun Entity.asFixtureComponent(fixtureComponentType: KClass<out FixtureComponent>): (Fixture) -> Unit {
        return { fixture ->
            val fixtureComponent = engine.createComponent(fixtureComponentType.java)
            fixture.userData = this
            fixtureComponent.with(fixture)
            add(fixtureComponent)
        }
    }

    // then I can use it as...
    world.body {
        circle(asFixtureComponent(HitBox::class)) {
            isSensor = true
            filter {
                groupIndex = FilterGroup.HIT_BOX_GROUP.num()
                categoryBits = CategoryBits.FRIENDLY_HIT_BOX.bits()
                maskBits = CategoryBits.ENEMY_PROJECTILE.bits32().toShort()
            }
        }
    }
```
The alternative you suggest would still work for me though, but I think the resultant game code would be slightly less nice.

**Comment by czyzby** [comment]
I can see why it's useful for you, but it does seem like a bit specific use case that would be used by barely any devs. I might be wrong though: if there are more feature requests - sure, don't see why not.

However, adding a `userObject` property to `FixtureDefinition` seems like a good idea - I rarely needed direct to access `Fixture` instances in my Box2D games beyond setting `userObject` and handling contacts. 

Side note: you can rewrite your code to use reified generics, so you can call the method like that: `asFixtureComponent<HitBox>()`.

**Comment by Jkly** [comment]
Yep, that seems like a reasonable decision - having access to the userObject may cover off most of the common use cases anyway.

**Comment by czyzby** [comment]
@Jkly I think I've addressed most of the issues. Can you take a look now?

**Comment by Jkly** [comment]
With `edge()` it'll be useful to have the component `x`, `y` params because there's an underlying JNI call that takes those.

Generally it looks great - it feels like a superior DSL implementation to `gdx-box2d-kotlin`. 

The only thing that would give me pause before switching over is that lack of access to instantiated Fixtures without calling another API (I need it for game-code to be able to disable/enable fixtures by altering the filter mask after creation), but I understand your viewpoint of wanting to see more use-cases first.

**Comment by czyzby** [comment]
> With `edge()` it'll be useful to have the component `x`, `y` params because there's an underlying JNI call that takes those.

You mean you want to replace `from` and `to` with 4 float parameters? Using `Vector2` for points seems more consistent with the rest of the API at this point.

> The only thing that would give me pause before switching over is that lack of access to instantiated Fixtures without calling another API

Well, instead of this:

```Kotlin
val body = world.body {
  circle { /* ... */ }
}
```

You can do this:

```Kotlin
val body = world.body { /* ... */ }
val fixture = body.circle { /* ... */ }
```

There's pretty much no performance penalty either way and both work similarly. I'd argue that code with callbacks would be less readable than simply creating required fixtures outside of the main `body` building block, but then again - that depends on the use case.

**Comment by Jkly** [comment]
> You mean you want to replace from and to with 4 float parameters?
Yes, to avoid forcing the user to create new `Vector2` objects. Maybe an optional function overload?

I wasn't suggesting the mechanism to be callbacks, just that it would be nice if I could use the main DSL and still get access to the Fixtures (however that would be).

All in all though, it looks good. And the benefits of focussing efforts on a single DSL in the community will probably outweigh this possibly niche use-case of mine.

**Comment by czyzby** [comment]
Makes sense, I'll add overloads similarly to how `chain` and `loop` are handled.

**Comment by czyzby** [comment]
@Jkly Can I close the issue now or is there anything else you'd change? Thanks for your review.

I can think of one way to address your issue that adding yet another argument to existing builder methods - adding `onCreate` callbacks to `FixtureDefinition` and `BodyDefinition`.

```Kotlin
// This is what I'd like to avoid:
world.body {
  circle(onCreate = { fixture -> /* Creates unclear program flow issues. */ }) {
    density = 0.5f
  }
}

// This is not that bad:
world.body {
  circle {
    density = 0.5f
    onCreate { fixture ->
      // ...
    }
  }
}
```

If you think it makes sense and would solve your problem, I have nothing against such callbacks API.

**Comment by Jkly** [comment]
The `onCreate()` idea would work for my use-case. I think it's worth adding for completeness, as it'll cover off all the use-cases I've come across so far.

Either way, I'm happy if you want to close the issue - the DSL is looking great!

**Comment by czyzby** [comment]
Great. This issue already got pretty big, so I'll cover the callbacks API in #65. Thanks.
